### PR TITLE
CAD Workshop Resources

### PR DESCRIPTION
**Pull request by tranjamin**

### CODE REVIEW

**Comment by tranjamin** [comment]
just another set of eyes to look over this one.
we'll probably aim to direct students to the readme, but we can also just send out other comms through mailing/fb

**Review by q-horton — CHANGES_REQUESTED** [review]
The repo is just for resources, not event promotion, this directory will be linked to via the event itself. I didn't look at the prt/stp files, but I assume they're up to scratch.

**Comment by tranjamin** [comment]
rewrote the readme a bit, check to see if this is what you want

**Review by q-horton — APPROVED** [review]
lgtm

**Pull request merged**
